### ISSUE TITLE
Bug 1151842: Linux B2G builds are missing from the site

### ISSUE THREAD

**Issue by pmclanahan** [mozilla/nocturnal#37]
They've moved the builds from FTP to a new system at taskcluster.net. See [bug 1151842](https://bugzilla.mozilla.org/show_bug.cgi?id=1151842) for details. Comments in the bug contain details for getting the download urls for builds from task cluster.

**Comment by fwenzel** [comment]
Seems pretty straightforward. Instead of scraping we'll do a little bit of REST API magic.

**Comment by pmclanahan** [comment]
Yeah. Seems easy enough. Just posted here in case some one with more time
than me gets a chance to knock it out before I can :)

**Comment by fwenzel** [comment]
"more time" is a relative term, but I can take it.

**Comment by pmclanahan** [comment]
You are truly a gentleman and a scholar.
